#!/usr/bin/env python3
"""Resolve a wallpaper's theme and publish it to the running desktop.

    apply.py [wallpaper-path-or-stem]     (default: the saved wallpaper)

Reads wallpapers/<stem>/theme.json + bar.json + kitty.conf (following "inherits" into
wallpapers/_presets/), writes the flattened result to
$XDG_CACHE_HOME/wallpaper_theme/current.json, which Quickshell watches
(quickshell/themes/Theme.qml) and repaints from, then updates the cheap
consumers: Firefox (chrome CSS in the profile, see firefox.py), kitty (colours, live) and Hyprland window borders (hyprctl eval). Missing theme
falls back to the "default" preset (Catppuccin Mocha). Safe to call often;
does nothing when the result did not change.
"""
import json, os, signal, subprocess, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import firefox
import zed

HOME = Path.home()
CFG = Path(os.environ.get("XDG_CONFIG_HOME", HOME / ".config"))
CACHE = Path(os.environ.get("XDG_CACHE_HOME", HOME / ".cache")) / "wallpaper_theme"
WP = CFG / "wallpapers"
SAVE = CFG / "scripts/wallpaper/wpsave.txt"
LIST = CFG / "scripts/wallpaper/list.sh"


def stem_dir(stem):
    """The wallpaper's folder: in wallpapers/, or in a folder added by the
    per-device wallpapers/local.conf (found through list.sh). Loose images have none."""
    try:
        out = subprocess.run([str(LIST)], capture_output=True, text=True, timeout=10).stdout
    except (OSError, subprocess.SubprocessError):
        out = ""
    for line in out.splitlines():
        f = Path(line)
        if f.stem == stem and f.parent.name == stem:
            return f.parent
    return WP / stem


def stem_of(arg):
    return Path(arg.strip()).stem


def load(stem, seen=()):
    for p in (stem_dir(stem) / "theme.json", WP / "_presets" / f"{stem}.json"):
        if p.is_file():
            t = json.loads(p.read_text())
            parent = t.get("inherits")
            if parent and parent not in seen:
                base = load(parent, seen + (stem,))
                if base:
                    for k in ("fonts", "style", "palette", "extra"):
                        merged = dict(base.get(k, {})); merged.update(t.get(k) or {})
                        t[k] = merged
                    for k in ("dark", "name"):
                        t.setdefault(k, base.get(k))
            return t
    return None


def folder_extras(stem, t):
    """Other files in the wallpaper's folder: bar.json -> t["bar"], kitty.conf -> t["kitty_extra"]."""
    d = stem_dir(stem)
    try:
        t["bar"] = {k: v for k, v in json.loads((d / "bar.json").read_text()).items() if k != "_"}
    except (OSError, ValueError):
        t["bar"] = {}
    try:
        t["kitty_extra"] = (d / "kitty.conf").read_text()
    except OSError:
        t["kitty_extra"] = ""


def kitty_conf(t):
    p = t["palette"]; fg = p["textPrimary"]; bg = p["background"]
    hues = ["panelDeep", "red", "green", "yellow", "blue", "violet", "cyan", "textSecondary"]
    lines = [f"# generated by scripts/theme/apply.py from {t.get('stem')}: do not edit",
             f"foreground {fg}", f"background {bg}", f"selection_foreground {bg}",
             f"selection_background {p['accent']}", f"cursor {p['accent']}", f"cursor_text_color {bg}",
             f"url_color {p['accent']}", f"active_border_color {p['accent']}",
             f"inactive_border_color {p['border']}", f"bell_border_color {p['yellow']}",
             f"active_tab_foreground {p.get('onAccent', bg)}", f"active_tab_background {p['accent']}",
             f"inactive_tab_foreground {fg}", f"inactive_tab_background {p['panel']}",
             f"tab_bar_background {p['panelDeep']}"]
    for i, k in enumerate(hues):
        lines.append(f"color{i} {p[k]}")
        lines.append(f"color{i + 8} {p[k]}")
    lines[-1] = f"color15 {fg}"
    extra = t.get("kitty_extra")
    if extra:
        lines.append(extra.rstrip("\n"))
    return "\n".join(lines) + "\n"


def write_if_changed(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        if path.read_text() == text:
            return False
    except OSError:
        pass
    path.write_text(text)  # in place (not renamed) so file watchers keep their watch
    return True


def main():
    arg = sys.argv[1] if len(sys.argv) > 1 else SAVE.read_text()
    stem = stem_of(arg)
    t = load(stem) or load("default")
    if not t:
        return
    t["stem"] = stem
    folder_extras(stem, t)
    changed = write_if_changed(CACHE / "current.json", json.dumps(t, indent=1))
    try:
        firefox.update(t, stem_dir(stem))  # tolerant: no Firefox/profile -> nothing
    except Exception as e:
        print(f"firefox theme: {e}", file=sys.stderr)
    try:
        zed.apply(t, stem, stem_dir(stem).parent, write_if_changed)  # tolerant: no Zed config dir -> nothing
    except Exception as e:
        print(f"zed theme: {e}", file=sys.stderr)
    if not changed:
        return
    if write_if_changed(CFG / "kitty/current-theme.conf", kitty_conf(t)):
        subprocess.run(["pkill", "-USR1", "-x", "kitty"], check=False)
    p = t["palette"]; c2 = (t.get("extra") or {}).get("accent2", p["blue"])
    lua = ('hl.config({ general = { col = { active_border = { colors = { "0xFF%s", "0xFF%s" }, angle = 45 }, '
           'inactive_border = "0xFF%s" } } })') % (p["accent"].lstrip("#"), c2.lstrip("#"), p["border"].lstrip("#"))
    subprocess.run(["hyprctl", "eval", lua], check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


if __name__ == "__main__":
    main()
